### ISSUE TITLE
Construct Ids should be unique

### ISSUE THREAD

**Issue by franco-bildungsfinder** [brefphp/constructs#1]
Hi 

I know you're still working on this and haven't released it yet. I already came across it and tried it out. 
It works great for cdk stacks that only create one function, but it fails when creating the second function in the same stack. 

`cdk synth` fails with
`There is already a Construct with name '${childName}' in ${typeName}${name.length > 0 ? ' [' + name + ']' : ''}`

If I am correct, this is because in layers.ts (https://github.com/brefphp/constructs/blob/main/src/layers.ts#L13 and Line 26 and 32) the id is hardcoded. I think they should be generated so that they are always unique.  Not sure how about doing that. 

Anyway, I just wanted to let you know. 
Thanks for all the cool work you do!

A long time happy bref user

**Comment by mnapoli** [comment]
Ohhh thank you for trying things out, that's super useful feedback!

I think I need to pass `this` instead of `scope` here:

https://github.com/brefphp/constructs/blob/75186b068831112d3addf37b27c572fa50024723/src/function/PhpFunction.ts#L47

that way the layer is sub-namespaced in each function.

I'll check that out!

**Comment by franco-bildungsfinder** [comment]
Just to confirm: Works perfectly now, thank you!

Sent you a little holiday gift via github sponsor.

**Comment by mnapoli** [comment]
@franco-bildungsfinder aaaawesome, thank you so much! Enjoy the holidays!
